/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMathExtended } from "./IMathExtended";
export type { MathExtended } from "./MathExtended";

export { IMathExtended__factory } from "./factories/IMathExtended__factory";
export { MathExtended__factory } from "./factories/MathExtended__factory";
