/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MathExtendedInterface extends ethers.utils.Interface {
  functions: {
    "add(uint256,uint256)": FunctionFragment;
    "addBulk(uint256[])": FunctionFragment;
    "getGcd(uint256,uint256)": FunctionFragment;
    "isPrime(uint256)": FunctionFragment;
    "mulDiv(uint256,uint256,uint256)": FunctionFragment;
    "swapAwesome(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "add",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addBulk",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getGcd",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPrime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mulDiv",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAwesome",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addBulk", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGcd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPrime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mulDiv", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapAwesome",
    data: BytesLike
  ): Result;

  events: {};
}

export class MathExtended extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MathExtendedInterface;

  functions: {
    add(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    addBulk(
      _values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getGcd(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isPrime(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mulDiv(
      _value1: BigNumberish,
      _value2: BigNumberish,
      _value3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    swapAwesome(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  add(
    _value1: BigNumberish,
    _value2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  addBulk(
    _values: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGcd(
    _value1: BigNumberish,
    _value2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isPrime(_value: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  mulDiv(
    _value1: BigNumberish,
    _value2: BigNumberish,
    _value3: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  swapAwesome(
    _value1: BigNumberish,
    _value2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  callStatic: {
    add(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addBulk(
      _values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGcd(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPrime(_value: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    mulDiv(
      _value1: BigNumberish,
      _value2: BigNumberish,
      _value3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapAwesome(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    add(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addBulk(
      _values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGcd(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPrime(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mulDiv(
      _value1: BigNumberish,
      _value2: BigNumberish,
      _value3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapAwesome(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    add(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addBulk(
      _values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGcd(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPrime(
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mulDiv(
      _value1: BigNumberish,
      _value2: BigNumberish,
      _value3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapAwesome(
      _value1: BigNumberish,
      _value2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
